name: fido2
description: Library to parse FIDO2 request / response and interactive with authenticators via CTAP2.
version: 1.0.0
repository: https://github.com/nfcim/fido2

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  asn1lib: ^1.6.5
  cbor: ^6.3.7
  convert: ^3.0.1
  crypto: ^3.0.6
  cryptography: ^2.7.0
  elliptic: ^0.3.11
  json_annotation: ^4.9.0
  pointycastle: ^4.0.0
  quiver: ^3.2.2

dev_dependencies:
  lints: ^4.0.0
  test: ^1.25.8
  dart_pcsc: ^2.0.2
  build_runner: ^2.6.0
  json_serializable: ^6.11.0
